export const meals = {
  breakfast: [
    {
      id: 1,
      name: 'Egg with slice fry',
      des: 'How we dream about our future',
      img: 'https://i.ibb.co/GQ4K0HR/breakfast1.png',
      price: 24,
    },
    {
      id: 2,
      name: 'Healthy Sladi Food',
      des: 'How we dream about our future',
      img: 'https://i.ibb.co/DfRWQBs/breakfast2.png',
      price: 13,
    },
    {
      id: 3,
      name: 'Sussy Tomatos',
      des: 'How we dream about our future',
      img: 'https://i.ibb.co/ZdW0HQv/breakfast3.png',
      price: 15,
    },
    {
      id: 4,
      name: 'Egg with Green Leafs',
      des: 'How we dream about our future',
      img: 'https://i.ibb.co/DV15Xf4/breakfast4.png',
      price: 9,
    },
    {
      id: 5,
      name: 'Bread Toast with egg fry',
      des: 'How we dream about our future',
      img: 'https://i.ibb.co/X3mnjgF/breakfast5.png',
      price: 10,
    },
    {
      id: 6,
      name: 'Egg with toast and Cheese',
      des: 'How we dream about our future',
      img: 'https://i.ibb.co/3YcNN5L/breakfast6.png',
      price: 27,
    },
  ],
  launch: [
    {
      id: 1,
      name: 'Beef with Tomato',
      des: 'How we dream about our future',
      img: 'https://i.ibb.co/NYqgdNJ/lunch1.png',
      price: 24,
    },
    {
      id: 2,
      name: 'Rice With Shrimp',
      des: 'How we dream about our future',
      img: 'https://i.ibb.co/sJNgCNK/lunch2.png',
      price: 13,
    },
    {
      id: 3,
      name: 'Healthy Salad',
      des: 'How we dream about our future',
      img: 'https://i.ibb.co/9gQWjvm/lunch3.png',
      price: 15,
    },
    {
      id: 4,
      name: 'Papad with Rice and Beef',
      des: 'How we dream about our future',
      img: 'https://i.ibb.co/b5D1rZn/lunch4.png',
      price: 9,
    },
    {
      id: 5,
      name: 'Chicken with French Fries',
      des: 'How we dream about our future',
      img: 'https://i.ibb.co/cwHpy76/lunch5.png',
      price: 10,
    },
    {
      id: 6,
      name: 'Toast With Salad',
      des: 'How we dream about our future',
      img: 'https://i.ibb.co/BPNjJvM/lunch6.png',
      price: 27,
    },
  ],
  dinner: [
    {
      id: 1,
      name: 'Healthy Saladi Dinner',
      des: 'How we dream about our future',
      img: 'https://i.ibb.co/HdbNQMs/dinner1.png',
      price: 24,
    },
    {
      id: 2,
      name: 'Fish With Healthy Salad',
      des: 'How we dream about our future',
      img: 'https://i.ibb.co/wy4HsZk/dinner2.png',
      price: 13,
    },
    {
      id: 3,
      name: 'Healthy Onion Dinner',
      des: 'How we dream about our future',
      img: 'https://i.ibb.co/9trCYgq/dinner3.png',
      price: 15,
    },
    {
      id: 4,
      name: 'Mixed of Non Veg With Cheese',
      des: 'How we dream about our future',
      img: 'https://i.ibb.co/fxmkKWg/dinner4.png',
      price: 9,
    },
    {
      id: 5,
      name: 'Healthy Carrots and Fish Slice',
      des: 'How we dream about our future',
      img: 'https://i.ibb.co/T1qhz9Y/dinner5.png',
      price: 10,
    },
    {
      id: 6,
      name: 'Healthy Salad With Fish',
      des: 'How we dream about our future',
      img: 'https://i.ibb.co/DtT5n4N/dinner6.png',
      price: 27,
    },
  ],
}
